import {describe,it,expect,beforeEach} from 'vitest';
import Database from 'better-sqlite3';
import {readFileSync} from 'node:fs';
import type {D1Database,D1PreparedStatement} from '@cloudflare/workers-types';
import {canonicalIban,mapPhysicalAccount,normalizeVs,reservePaymentReference,referenceScope} from './paymentReferences';
function fixture(){const sqlite=new Database(':memory:');sqlite.pragma('foreign_keys = ON');for(const f of ['0001_schema','0011_complete_bank_facts','0012_payment_references'])sqlite.exec(readFileSync(new URL(`../migrations/${f}.sql`,import.meta.url),'utf8'));const values=new WeakMap<object,{sql:string;args:unknown[]}>();const prepare=(sql:string)=>{const stmt={bind(...args:unknown[]){values.set(stmt,{sql,args});return stmt;},async first(){const v=values.get(stmt)!;return sqlite.prepare(v.sql).get(...v.args)??null;},async run(){const v=values.get(stmt)!;return sqlite.prepare(v.sql).run(...v.args);}};values.set(stmt,{sql,args:[]});return stmt as unknown as D1PreparedStatement;};const db={prepare,async batch(statements:D1PreparedStatement[]){return sqlite.transaction(()=>statements.map(s=>{const v=values.get(s)!;return sqlite.prepare(v.sql).run(...v.args);} ))();}} as unknown as D1Database;sqlite.exec("INSERT INTO bank_accounts(id,account_number,pairing_code) VALUES(1,'19-2000145399/0800','alias-1'),(2,'CZ6508000000192000145399','alias-2'),(3,'1234/2010','other')");return {db,sqlite};}
describe('permanent physical account registry',()=>{
 it('normalizes leading zeros, aliases, and validates IBAN',()=>{expect(normalizeVs('000123')).toBe('123');expect(canonicalIban('19-2000145399/0800')).toBe('CZ6508000000192000145399');expect(()=>canonicalIban('CZ0008000000192000145399')).toThrow();});
 it('requires cutover, independent grants, durable retry and no duplicate VS',async()=>{const {db,sqlite}=fixture();const p=await mapPhysicalAccount(db,1);expect(await mapPhysicalAccount(db,2)).toBe(p);expect(await mapPhysicalAccount(db,3)).not.toBe(p);await expect(referenceScope(db,1,'a')).rejects.toThrow('forbidden');sqlite.prepare('INSERT INTO payment_reference_grants VALUES(?,?)').run(p,'a');expect(await referenceScope(db,2,'a')).toBe(p);await expect(reservePaymentReference(db,p,'a','one','a'.repeat(64))).rejects.toThrow('registry_locked');sqlite.prepare('UPDATE physical_accounts SET allocation_enabled=1 WHERE id=?').run(p);const [a,b]=await Promise.all([reservePaymentReference(db,p,'a','one','a'.repeat(64)),reservePaymentReference(db,p,'b','two','b'.repeat(64))]);expect(a.normalized_vs).not.toBe(b.normalized_vs);expect(await reservePaymentReference(db,p,'a','one','a'.repeat(64))).toEqual(a);await expect(reservePaymentReference(db,p,'a','one','c'.repeat(64))).rejects.toThrow('conflict');expect(()=>sqlite.prepare('DELETE FROM payment_references').run()).toThrow('permanent');});
 it('optionally reserves requested VS and rejects another purpose without unlocking ownership',async()=>{const {db,sqlite}=fixture(),p=await mapPhysicalAccount(db,1);sqlite.prepare('UPDATE physical_accounts SET allocation_enabled=1 WHERE id=?').run(p);const first=await reservePaymentReference(db,p,'a','requested','a'.repeat(64),'0004321');expect(first.normalized_vs).toBe('4321');await expect(reservePaymentReference(db,p,'b','another-purpose','b'.repeat(64),'4321')).rejects.toThrow('conflict');expect(await reservePaymentReference(db,p,'a','requested','a'.repeat(64),'4321')).toEqual(first);expect(sqlite.prepare('SELECT allocation_enabled FROM physical_accounts WHERE id=?').get(p)).toEqual({allocation_enabled:1});});
 it('historical collisions lock the account and exhaustion is explicit',async()=>{const {db,sqlite}=fixture(),p=await mapPhysicalAccount(db,1);await reservePaymentReference(db,p,'a','legacy','a'.repeat(64),'00042',true);await expect(reservePaymentReference(db,p,'b','legacy','b'.repeat(64),'42',true)).rejects.toThrow('conflict');expect(sqlite.prepare('SELECT count(*) n FROM payment_reference_conflicts').get()).toEqual({n:1});sqlite.prepare('UPDATE physical_accounts SET allocation_enabled=1,next_vs=10000000000 WHERE id=?').run(p);await expect(reservePaymentReference(db,p,'a','new','a'.repeat(64))).rejects.toThrow('exhausted');});
 it('backup/restore keeps registry locked and cannot reuse an imported symbol',async()=>{const {db,sqlite}=fixture(),p=await mapPhysicalAccount(db,1);await reservePaymentReference(db,p,'a','legacy','a'.repeat(64),'1',true);sqlite.prepare('UPDATE physical_accounts SET allocation_enabled=1 WHERE id=?').run(p);const r=await reservePaymentReference(db,p,'a','new','b'.repeat(64));expect(r.normalized_vs).not.toBe('1');expect(()=>sqlite.prepare('UPDATE bank_accounts SET account_number=? WHERE id=1').run('1234/2010')).toThrow('immutable');});
});
